royalmo/itic-copilot

_locales/en/messages.json

I fixed some typos in the en/messages.json

Locales EN: Fixed typos.

---

_locales/ca/messages.json
_locales/es/messages.json

I translated _locales/en/messages.json into catalan and spanish.

Catalan and Spanish translations

---

_locales/it/messages.json

Marcello
Marcello: What is it?
What you doing?
Marcello: Holding a pistol
MAMMA MIA! Marcello that's not how you hold a pistol
Marcello: What do you mean
This is how you hold a pistol (epic italian hold)
Alberto! Come and look at Marcello
M A M M A M I A! *italian anger*

Italian translation done

---

_locales/fr/messages.json

Allons enfant de la patrie
Le jour de gloire (le jour de gloire) est arrivé (est arrivé)
Contre nous de la tyrannie
L'étendart sanglant est levé
L'étendart sanglant est levé
Entendez-vous dans vos campagnes
Mugir ces féroces (soldats) soldats
Ils viennent jusque dans vos bras
Égorger vos fils et vos compagnes
Aux (armes citoyens) armes citoyens, formez vos bataillons
Marchons, oui marchons
Qu'un sang impur abreuve nos sillons, sillons
Ouh-ouh-ouh

French translation done

---

_locales/de/messages.json

The most widely known quotation from Hitler's public orations is taken from his speech in the German Reichstag on 30 January 1939. Referring to the Jewish question, it contains the macabre prophecy: "Today I will be once more a prophet: if the international Jewish financiers in and outside Europe should succeed in plunging the nations once more into a world war, then the result will not be the Bolshevizing of the earth, and thus the victory of Jewry, but the annihilation of the Jewish race in Europe!"(1) This statement has been taken as evidence that in early 1939 Hitler already intended to exploit the conditions of a future war to annihilate the Jews, at least those under German rule.

German translation done

---

js/download_popup.js
js/download_subject.js
js/fetch_files.js
js/replace_html.js
js/tree.js
manifest.json

This branch is to add contenttype-image support when downloading an entire subject.

Contenttype-image support in OCWiTIC

---

_locales/en/messages.json
js/download_subject.js
js/replace_html.js
js/tree.js

Now full quadrimester download is available!

Download entire quadrimester

---

_locales/ca/messages.json
_locales/de/messages.json
_locales/en/messages.json
_locales/es/messages.json
_locales/fr/messages.json
_locales/it/messages.json
js/download_popup.js
js/download_subject.js
js/fetch_files.js
js/replace_html.js

Added cancel button when downloading

---

_locales/ca/messages.json
_locales/de/messages.json
_locales/en/messages.json
_locales/es/messages.json
_locales/fr/messages.json
_locales/it/messages.json
js/download_popup.js
js/download_subject.js
js/fetch_files.js
js/replace_html.js
js/tree.js

But browser extension locales is a piece of ***** because you can't have multiple files and folders. AND you can put common identifiers, so it's impossible to work this way.

Reorganized locales + small fix in alert_timeout.

---

js/basics.js
js/escriny/editor.js
js/fnon_controller.js
js/ocw/file_downloader.js
manifest.json

This way, we give a use of the settings menu!

Integrate user preferences on OCW and SVN

---

js/autologger.js
js/escriny/escriny_autologin.js
js/settings.js
js/upc_autologin.js
manifest.json

Maybe it could be improved in the future, but it's enough for now.

Added autologin in UPCnet

---

_locales/en/messages.json
html/load_schedule.html
html/user_interface.html
include/localize.js
js/basics.js
js/escriny/editor.js
js/escriny/escriny_autologin.js
js/timetables/redirect.js
js/timetables/selector.js
js/upc_autologin.js
js/user_interface.js

All tags will be added, so the only thing that would be left to do is to fill the json file for each language.

Added (html) support for localisation.

---

_locales/ca/messages.json
_locales/en/messages.json
_locales/es/messages.json
css/user_interface.css
html/user_interface.html

Translated to both languages and fixed some display bugs for when the text is too large or too small.

Translations to catalan and spanish for v1.7

---

_locales/ca/messages.json
_locales/en/messages.json
_locales/es/messages.json
config/subjects.json
css/user_interface.css
html/user_interface.html
js/basics.js
js/user_interface.js

The subjects are now listed in the settings menu.
This PR has been done in a way that the code can mostly be reused.

Subjects are shown on the settings menu

---

_locales/ca/messages.json
_locales/en/messages.json
_locales/es/messages.json
html/course_guides.html
js/basics.js
js/settings.js
js/student_plan/viewer_epsem.js
js/student_plan/viewer_upcweb.js
js/timetables/redirect.js
js/user_interface.js
manifest.json

Also added a partial renderer and tested await calls to settings (they are more beautiful).
It needs to be tested in Firefox and fix a line break on the spanish web.

Show your subjects in course guides

---

README.md
manifest.json

The extension's version has been modified, and the README too.

Update and prepare README for next version

---

_locales/ca/messages.json
_locales/en/messages.json
_locales/es/messages.json
config/default_settings.json
html/ocw_landpage.html
html/user_interface.html
js/fnon_controller.js
js/ocw/file_downloader.js
js/ocw/html_replacer.js
js/ocw/landpage.js
manifest.json

OCW has a landpage with the preferred subjects and a download all button.

Made OCW's landpage

---

_locales/ca/messages.json
_locales/en/messages.json
_locales/es/messages.json
html/escriny_landpage.html
js/escriny/landpage.js
manifest.json

Added escriny's landing page.
It was a little bit tricky because an AJAX request would be denied (because the server is special). So I had to use an iframe and all that stuff.
But it worked!!

Added escriny's landing page

---

README.md
_locales/ca/messages.json
_locales/en/messages.json
_locales/es/messages.json
config/default_settings.json
html/user_interface.html
js/escriny/landpage.js
manifest.json

README has been updated with some screenshots.
Some bug fixes that were left undone.

Bug fixes & prepared v1.8

---

html/load_schedule.html

@FlyingKoala01 found that exam dates weren't showing on the selected schedule.
The reason is weird but explained in #71 .
Here is the fix.

Fix: schedule wasn't showing exam dates

---

js/ocw/file_downloader.js
js/ocw/landpage.js

The progress updater for when the files were downloading was not great, as it didn't use async functions. Now it's fixed and we can clearly see what it its doing when downloading a subject, folder or quadrimester.

Fixed: OCW download progress update

---

css/user_interface.css
html/user_interface.html

I just changed the font size a little big. It's more a patch than a fix.

Fix: firefox landpage was too big.

---

html/ocw_landpage.html
js/ocw/landpage.js

Now your subjects can be opened in a new tab, and everything that an anchor does.

OCW's landpage hrefs are now anchors.

---

html/user_interface.html
manifest.json

The manifest version has been updated.
The _NEW_ disclaimer on the settings menu should be changed.
Browser compatibility should be tested.

Update and publish 1.8.3

---

config/links.json
html/user_interface.html
js/user_interface.js
manifest.json

Fixed calendar to automatic year.

---

README.md

Added firefox instructions on README
